/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DexRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "MAX_PARTNER_FEE_BPS"
      | "PROTOCOL_FEE_BPS"
      | "WAVAX"
      | "adapters"
      | "findBestRoute"
      | "getPartnerAccumulatedFees"
      | "getQuote"
      | "owner"
      | "partnerAccumulatedFees"
      | "partnerRegistry"
      | "registerAdapter"
      | "registeredDexes"
      | "removeAdapter"
      | "renounceOwnership"
      | "setPartnerRegistry"
      | "swapAVAXForTokens"
      | "swapAVAXForTokensWithPartner"
      | "swapBestRoute"
      | "swapBestRouteWithPartner"
      | "swapOnDex"
      | "swapOnDexWithPartner"
      | "swapTokensForAVAX"
      | "swapTokensForAVAXWithPartner"
      | "transferOwnership"
      | "withdrawPartnerFees"
      | "withdrawProtocolFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdapterRegistered"
      | "AdapterRemoved"
      | "OwnershipTransferred"
      | "PartnerFeesAccumulated"
      | "PartnerFeesWithdrawn"
      | "ProtocolFeesWithdrawn"
      | "SwapExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PARTNER_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "WAVAX", values?: undefined): string;
  encodeFunctionData(functionFragment: "adapters", values: [string]): string;
  encodeFunctionData(
    functionFragment: "findBestRoute",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPartnerAccumulatedFees",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuote",
    values: [string, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "partnerAccumulatedFees",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "partnerRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerAdapter",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredDexes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAdapter",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPartnerRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapAVAXForTokens",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapAVAXForTokensWithPartner",
    values: [AddressLike, BigNumberish, AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapBestRoute",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapBestRouteWithPartner",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapOnDex",
    values: [
      string,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapOnDexWithPartner",
    values: [
      string,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapTokensForAVAX",
    values: [AddressLike, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapTokensForAVAXWithPartner",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPartnerFees",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawProtocolFees",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PARTNER_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "WAVAX", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "adapters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "findBestRoute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPartnerAccumulatedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getQuote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "partnerAccumulatedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "partnerRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredDexes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPartnerRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapAVAXForTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapAVAXForTokensWithPartner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapBestRoute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapBestRouteWithPartner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapOnDex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapOnDexWithPartner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapTokensForAVAX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapTokensForAVAXWithPartner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPartnerFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawProtocolFees",
    data: BytesLike
  ): Result;
}

export namespace AdapterRegisteredEvent {
  export type InputTuple = [dexName: string, adapter: AddressLike];
  export type OutputTuple = [dexName: string, adapter: string];
  export interface OutputObject {
    dexName: string;
    adapter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdapterRemovedEvent {
  export type InputTuple = [dexName: string];
  export type OutputTuple = [dexName: string];
  export interface OutputObject {
    dexName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PartnerFeesAccumulatedEvent {
  export type InputTuple = [
    partner: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [partner: string, token: string, amount: bigint];
  export interface OutputObject {
    partner: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PartnerFeesWithdrawnEvent {
  export type InputTuple = [
    partner: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [partner: string, token: string, amount: bigint];
  export interface OutputObject {
    partner: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolFeesWithdrawnEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [token: string, amount: bigint, recipient: string];
  export interface OutputObject {
    token: string;
    amount: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapExecutedEvent {
  export type InputTuple = [
    user: AddressLike,
    tokenIn: AddressLike,
    tokenOut: AddressLike,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    dexUsed: string,
    protocolFeeCollected: BigNumberish,
    partnerFeeCollected: BigNumberish,
    partner: AddressLike
  ];
  export type OutputTuple = [
    user: string,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    amountOut: bigint,
    dexUsed: string,
    protocolFeeCollected: bigint,
    partnerFeeCollected: bigint,
    partner: string
  ];
  export interface OutputObject {
    user: string;
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    amountOut: bigint;
    dexUsed: string;
    protocolFeeCollected: bigint;
    partnerFeeCollected: bigint;
    partner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DexRouter extends BaseContract {
  connect(runner?: ContractRunner | null): DexRouter;
  waitForDeployment(): Promise<this>;

  interface: DexRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  MAX_PARTNER_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  PROTOCOL_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  WAVAX: TypedContractMethod<[], [string], "view">;

  adapters: TypedContractMethod<[arg0: string], [string], "view">;

  findBestRoute: TypedContractMethod<
    [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish],
    [[string, bigint] & { bestDexName: string; bestAmountOut: bigint }],
    "view"
  >;

  getPartnerAccumulatedFees: TypedContractMethod<
    [partner: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  getQuote: TypedContractMethod<
    [
      dexName: string,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish
    ],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  partnerAccumulatedFees: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  partnerRegistry: TypedContractMethod<[], [string], "view">;

  registerAdapter: TypedContractMethod<
    [dexName: string, adapter: AddressLike],
    [void],
    "nonpayable"
  >;

  registeredDexes: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  removeAdapter: TypedContractMethod<[dexName: string], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPartnerRegistry: TypedContractMethod<
    [_partnerRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  swapAVAXForTokens: TypedContractMethod<
    [tokenOut: AddressLike, minAmountOut: BigNumberish, recipient: AddressLike],
    [bigint],
    "payable"
  >;

  swapAVAXForTokensWithPartner: TypedContractMethod<
    [
      tokenOut: AddressLike,
      minAmountOut: BigNumberish,
      recipient: AddressLike,
      partnerId: string,
      partnerFeeBps: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  swapBestRoute: TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      recipient: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  swapBestRouteWithPartner: TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      recipient: AddressLike,
      partnerId: string,
      partnerFeeBps: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  swapOnDex: TypedContractMethod<
    [
      dexName: string,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      recipient: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  swapOnDexWithPartner: TypedContractMethod<
    [
      dexName: string,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      recipient: AddressLike,
      partnerId: string,
      partnerFeeBps: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  swapTokensForAVAX: TypedContractMethod<
    [
      tokenIn: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      recipient: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  swapTokensForAVAXWithPartner: TypedContractMethod<
    [
      tokenIn: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      recipient: AddressLike,
      partnerId: string,
      partnerFeeBps: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawPartnerFees: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawProtocolFees: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PARTNER_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROTOCOL_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WAVAX"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "adapters"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "findBestRoute"
  ): TypedContractMethod<
    [tokenIn: AddressLike, tokenOut: AddressLike, amountIn: BigNumberish],
    [[string, bigint] & { bestDexName: string; bestAmountOut: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPartnerAccumulatedFees"
  ): TypedContractMethod<
    [partner: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getQuote"
  ): TypedContractMethod<
    [
      dexName: string,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "partnerAccumulatedFees"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "partnerRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAdapter"
  ): TypedContractMethod<
    [dexName: string, adapter: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registeredDexes"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "removeAdapter"
  ): TypedContractMethod<[dexName: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPartnerRegistry"
  ): TypedContractMethod<[_partnerRegistry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "swapAVAXForTokens"
  ): TypedContractMethod<
    [tokenOut: AddressLike, minAmountOut: BigNumberish, recipient: AddressLike],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "swapAVAXForTokensWithPartner"
  ): TypedContractMethod<
    [
      tokenOut: AddressLike,
      minAmountOut: BigNumberish,
      recipient: AddressLike,
      partnerId: string,
      partnerFeeBps: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "swapBestRoute"
  ): TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      recipient: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapBestRouteWithPartner"
  ): TypedContractMethod<
    [
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      recipient: AddressLike,
      partnerId: string,
      partnerFeeBps: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapOnDex"
  ): TypedContractMethod<
    [
      dexName: string,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      recipient: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapOnDexWithPartner"
  ): TypedContractMethod<
    [
      dexName: string,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      recipient: AddressLike,
      partnerId: string,
      partnerFeeBps: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapTokensForAVAX"
  ): TypedContractMethod<
    [
      tokenIn: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      recipient: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapTokensForAVAXWithPartner"
  ): TypedContractMethod<
    [
      tokenIn: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      recipient: AddressLike,
      partnerId: string,
      partnerFeeBps: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPartnerFees"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawProtocolFees"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdapterRegistered"
  ): TypedContractEvent<
    AdapterRegisteredEvent.InputTuple,
    AdapterRegisteredEvent.OutputTuple,
    AdapterRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AdapterRemoved"
  ): TypedContractEvent<
    AdapterRemovedEvent.InputTuple,
    AdapterRemovedEvent.OutputTuple,
    AdapterRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PartnerFeesAccumulated"
  ): TypedContractEvent<
    PartnerFeesAccumulatedEvent.InputTuple,
    PartnerFeesAccumulatedEvent.OutputTuple,
    PartnerFeesAccumulatedEvent.OutputObject
  >;
  getEvent(
    key: "PartnerFeesWithdrawn"
  ): TypedContractEvent<
    PartnerFeesWithdrawnEvent.InputTuple,
    PartnerFeesWithdrawnEvent.OutputTuple,
    PartnerFeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolFeesWithdrawn"
  ): TypedContractEvent<
    ProtocolFeesWithdrawnEvent.InputTuple,
    ProtocolFeesWithdrawnEvent.OutputTuple,
    ProtocolFeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "SwapExecuted"
  ): TypedContractEvent<
    SwapExecutedEvent.InputTuple,
    SwapExecutedEvent.OutputTuple,
    SwapExecutedEvent.OutputObject
  >;

  filters: {
    "AdapterRegistered(string,address)": TypedContractEvent<
      AdapterRegisteredEvent.InputTuple,
      AdapterRegisteredEvent.OutputTuple,
      AdapterRegisteredEvent.OutputObject
    >;
    AdapterRegistered: TypedContractEvent<
      AdapterRegisteredEvent.InputTuple,
      AdapterRegisteredEvent.OutputTuple,
      AdapterRegisteredEvent.OutputObject
    >;

    "AdapterRemoved(string)": TypedContractEvent<
      AdapterRemovedEvent.InputTuple,
      AdapterRemovedEvent.OutputTuple,
      AdapterRemovedEvent.OutputObject
    >;
    AdapterRemoved: TypedContractEvent<
      AdapterRemovedEvent.InputTuple,
      AdapterRemovedEvent.OutputTuple,
      AdapterRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PartnerFeesAccumulated(address,address,uint256)": TypedContractEvent<
      PartnerFeesAccumulatedEvent.InputTuple,
      PartnerFeesAccumulatedEvent.OutputTuple,
      PartnerFeesAccumulatedEvent.OutputObject
    >;
    PartnerFeesAccumulated: TypedContractEvent<
      PartnerFeesAccumulatedEvent.InputTuple,
      PartnerFeesAccumulatedEvent.OutputTuple,
      PartnerFeesAccumulatedEvent.OutputObject
    >;

    "PartnerFeesWithdrawn(address,address,uint256)": TypedContractEvent<
      PartnerFeesWithdrawnEvent.InputTuple,
      PartnerFeesWithdrawnEvent.OutputTuple,
      PartnerFeesWithdrawnEvent.OutputObject
    >;
    PartnerFeesWithdrawn: TypedContractEvent<
      PartnerFeesWithdrawnEvent.InputTuple,
      PartnerFeesWithdrawnEvent.OutputTuple,
      PartnerFeesWithdrawnEvent.OutputObject
    >;

    "ProtocolFeesWithdrawn(address,uint256,address)": TypedContractEvent<
      ProtocolFeesWithdrawnEvent.InputTuple,
      ProtocolFeesWithdrawnEvent.OutputTuple,
      ProtocolFeesWithdrawnEvent.OutputObject
    >;
    ProtocolFeesWithdrawn: TypedContractEvent<
      ProtocolFeesWithdrawnEvent.InputTuple,
      ProtocolFeesWithdrawnEvent.OutputTuple,
      ProtocolFeesWithdrawnEvent.OutputObject
    >;

    "SwapExecuted(address,address,address,uint256,uint256,string,uint256,uint256,address)": TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;
    SwapExecuted: TypedContractEvent<
      SwapExecutedEvent.InputTuple,
      SwapExecutedEvent.OutputTuple,
      SwapExecutedEvent.OutputObject
    >;
  };
}
