/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPangolinFactory,
  IPangolinFactoryInterface,
} from "../../../../contracts/adapters/PangolinAdapter.sol/IPangolinFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenB",
        type: "address",
      },
    ],
    name: "getPair",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPangolinFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IPangolinFactoryInterface {
    return new Interface(_abi) as IPangolinFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPangolinFactory {
    return new Contract(address, _abi, runner) as unknown as IPangolinFactory;
  }
}
