/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as pangolin from "./pangolin";
export type { pangolin };
import type * as traderjoe from "./traderjoe";
export type { traderjoe };
export type { IDexAdapter } from "./IDexAdapter";
export type { IWAVAX } from "./IWAVAX";
