/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockDexAdapter__factory } from "./MockDexAdapter__factory";
export { MockERC20__factory } from "./MockERC20__factory";
