/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPangolinFactory } from "./IPangolinFactory";
export type { PangolinAdapter } from "./PangolinAdapter";
