/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as pangolinV2AdapterSol from "./PangolinV2Adapter.sol";
export type { pangolinV2AdapterSol };
import type * as traderJoeV1AdapterSol from "./TraderJoeV1Adapter.sol";
export type { traderJoeV1AdapterSol };
