/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDexAdapter__factory } from "./IDexAdapter__factory";
export { IWAVAX__factory } from "./IWAVAX__factory";
