/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILBRouter,
  ILBRouterInterface,
} from "../../../../contracts/interfaces/traderjoe/ILBRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "contract IERC20",
        name: "tokenB",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "binStep",
        type: "uint16",
      },
    ],
    name: "getLBPair",
    outputs: [
      {
        internalType: "contract ILBPair",
        name: "pair",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ILBPair",
        name: "lbPair",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "swapForY",
        type: "bool",
      },
    ],
    name: "getSwapIn",
    outputs: [
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "feesIn",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ILBPair",
        name: "lbPair",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "swapForY",
        type: "bool",
      },
    ],
    name: "getSwapOut",
    outputs: [
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "feesIn",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "amountIn",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountOutMin",
            type: "uint256",
          },
          {
            internalType: "uint256[]",
            name: "pairBinSteps",
            type: "uint256[]",
          },
          {
            internalType: "contract IERC20[]",
            name: "tokenPath",
            type: "address[]",
          },
          {
            internalType: "address",
            name: "to",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
        ],
        internalType: "struct ILBRouter.LBSwapExactInParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "swapExactTokensForTokens",
    outputs: [
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "amountOut",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountInMax",
            type: "uint256",
          },
          {
            internalType: "uint256[]",
            name: "pairBinSteps",
            type: "uint256[]",
          },
          {
            internalType: "contract IERC20[]",
            name: "tokenPath",
            type: "address[]",
          },
          {
            internalType: "address",
            name: "to",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
        ],
        internalType: "struct ILBRouter.LBSwapExactOutParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "swapTokensForExactTokens",
    outputs: [
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILBRouter__factory {
  static readonly abi = _abi;
  static createInterface(): ILBRouterInterface {
    return new Interface(_abi) as ILBRouterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ILBRouter {
    return new Contract(address, _abi, runner) as unknown as ILBRouter;
  }
}
