/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ILBPairInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getActiveId"
      | "getBinStep"
      | "getReserves"
      | "getSwapIn"
      | "getSwapOut"
      | "getTokenX"
      | "getTokenY"
      | "swap"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getActiveId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBinStep",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSwapIn",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSwapOut",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getTokenX", values?: undefined): string;
  encodeFunctionData(functionFragment: "getTokenY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [boolean, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getActiveId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBinStep", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSwapIn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSwapOut", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTokenX", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTokenY", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
}

export interface ILBPair extends BaseContract {
  connect(runner?: ContractRunner | null): ILBPair;
  waitForDeployment(): Promise<this>;

  interface: ILBPairInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getActiveId: TypedContractMethod<[], [bigint], "view">;

  getBinStep: TypedContractMethod<[], [bigint], "view">;

  getReserves: TypedContractMethod<
    [],
    [[bigint, bigint] & { reserveX: bigint; reserveY: bigint }],
    "view"
  >;

  getSwapIn: TypedContractMethod<
    [tokenIn: AddressLike, amountOut: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        amountIn: bigint;
        feesIn: bigint;
        feesOutOfBin: bigint;
      }
    ],
    "view"
  >;

  getSwapOut: TypedContractMethod<
    [tokenIn: AddressLike, amountIn: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        amountOut: bigint;
        feesIn: bigint;
        feesOutOfBin: bigint;
      }
    ],
    "view"
  >;

  getTokenX: TypedContractMethod<[], [string], "view">;

  getTokenY: TypedContractMethod<[], [string], "view">;

  swap: TypedContractMethod<
    [swapForY: boolean, to: AddressLike],
    [
      [string[], bigint, bigint] & {
        swapDebris: string[];
        amountIn: bigint;
        amountOut: bigint;
      }
    ],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getActiveId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBinStep"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReserves"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { reserveX: bigint; reserveY: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSwapIn"
  ): TypedContractMethod<
    [tokenIn: AddressLike, amountOut: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        amountIn: bigint;
        feesIn: bigint;
        feesOutOfBin: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSwapOut"
  ): TypedContractMethod<
    [tokenIn: AddressLike, amountIn: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        amountOut: bigint;
        feesIn: bigint;
        feesOutOfBin: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenX"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTokenY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "swap"
  ): TypedContractMethod<
    [swapForY: boolean, to: AddressLike],
    [
      [string[], bigint, bigint] & {
        swapDebris: string[];
        amountIn: bigint;
        amountOut: bigint;
      }
    ],
    "nonpayable"
  >;

  filters: {};
}
