/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace ILBRouter {
  export type LBSwapExactInParamsStruct = {
    amountIn: BigNumberish;
    amountOutMin: BigNumberish;
    pairBinSteps: BigNumberish[];
    tokenPath: AddressLike[];
    to: AddressLike;
    deadline: BigNumberish;
  };

  export type LBSwapExactInParamsStructOutput = [
    amountIn: bigint,
    amountOutMin: bigint,
    pairBinSteps: bigint[],
    tokenPath: string[],
    to: string,
    deadline: bigint
  ] & {
    amountIn: bigint;
    amountOutMin: bigint;
    pairBinSteps: bigint[];
    tokenPath: string[];
    to: string;
    deadline: bigint;
  };

  export type LBSwapExactOutParamsStruct = {
    amountOut: BigNumberish;
    amountInMax: BigNumberish;
    pairBinSteps: BigNumberish[];
    tokenPath: AddressLike[];
    to: AddressLike;
    deadline: BigNumberish;
  };

  export type LBSwapExactOutParamsStructOutput = [
    amountOut: bigint,
    amountInMax: bigint,
    pairBinSteps: bigint[],
    tokenPath: string[],
    to: string,
    deadline: bigint
  ] & {
    amountOut: bigint;
    amountInMax: bigint;
    pairBinSteps: bigint[];
    tokenPath: string[];
    to: string;
    deadline: bigint;
  };
}

export interface ILBRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getLBPair"
      | "getSwapIn"
      | "getSwapOut"
      | "swapExactTokensForTokens"
      | "swapTokensForExactTokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getLBPair",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSwapIn",
    values: [AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getSwapOut",
    values: [AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactTokensForTokens",
    values: [ILBRouter.LBSwapExactInParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "swapTokensForExactTokens",
    values: [ILBRouter.LBSwapExactOutParamsStruct]
  ): string;

  decodeFunctionResult(functionFragment: "getLBPair", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSwapIn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSwapOut", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapExactTokensForTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapTokensForExactTokens",
    data: BytesLike
  ): Result;
}

export interface ILBRouter extends BaseContract {
  connect(runner?: ContractRunner | null): ILBRouter;
  waitForDeployment(): Promise<this>;

  interface: ILBRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getLBPair: TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike, binStep: BigNumberish],
    [string],
    "view"
  >;

  getSwapIn: TypedContractMethod<
    [lbPair: AddressLike, amountOut: BigNumberish, swapForY: boolean],
    [[bigint, bigint] & { amountIn: bigint; feesIn: bigint }],
    "view"
  >;

  getSwapOut: TypedContractMethod<
    [lbPair: AddressLike, amountIn: BigNumberish, swapForY: boolean],
    [[bigint, bigint] & { amountOut: bigint; feesIn: bigint }],
    "view"
  >;

  swapExactTokensForTokens: TypedContractMethod<
    [params: ILBRouter.LBSwapExactInParamsStruct],
    [bigint],
    "nonpayable"
  >;

  swapTokensForExactTokens: TypedContractMethod<
    [params: ILBRouter.LBSwapExactOutParamsStruct],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getLBPair"
  ): TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike, binStep: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSwapIn"
  ): TypedContractMethod<
    [lbPair: AddressLike, amountOut: BigNumberish, swapForY: boolean],
    [[bigint, bigint] & { amountIn: bigint; feesIn: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSwapOut"
  ): TypedContractMethod<
    [lbPair: AddressLike, amountIn: BigNumberish, swapForY: boolean],
    [[bigint, bigint] & { amountOut: bigint; feesIn: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "swapExactTokensForTokens"
  ): TypedContractMethod<
    [params: ILBRouter.LBSwapExactInParamsStruct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapTokensForExactTokens"
  ): TypedContractMethod<
    [params: ILBRouter.LBSwapExactOutParamsStruct],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
