#!/bin/bash
# GitHub CLI commands to create Phase 1 issues
# Make sure you're logged in: gh auth login

# Note: These commands are auto-generated from .github/phase1-issues/*.md files
# Run them one by one or all at once after reviewing

echo "⚠️  IMPORTANT: Review these commands before running!"
echo "You need to be logged into GitHub CLI: gh auth login"
echo "You also need appropriate permissions on the repository."
echo

echo "To create the GitHub project board first:"
echo "gh project create --owner danaszova --title \"Phase 1: Infrastructure Recovery\" --description \"Fix root cause issues with DEX addresses and adapters\" --visibility PUBLIC"
echo

echo "Then create the issues:"
echo

# Commands would be generated by the Python script
# For now, here are manual instructions:
echo "Manual creation instructions:"
echo "1. Go to https://github.com/danaszova/avax-router/issues"
echo "2. Click 'New issue' for each ticket in .github/phase1-issues/"
echo "3. Copy/paste the content from each .md file"
echo "4. Add appropriate labels (infrastructure, contracts, api, testing, documentation, phase1)"
echo "5. Set priority based on ticket (Critical, High, Medium-High, Medium)"
echo

echo "After creating issues, add them to the project board:"
echo "1. Go to your project board"
echo "2. Click 'Add item'"
echo "3. Search for each issue and add it"
echo "4. Set initial status to 'Backlog'"
echo

echo "✅ Setup complete! Start with Ticket 1 (critical path)."
