/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPangolinPair__factory } from "./IPangolinPair__factory";
export { IPangolinRouter__factory } from "./IPangolinRouter__factory";
